In [3]:
import numpy as np
np.random.seed(42)

In [4]:
X = np.random.randn(3, 4)
print("X =")
print(X)

X =
[[ 0.49671415 -0.1382643   0.64768854  1.52302986]
 [-0.23415337 -0.23413696  1.57921282  0.76743473]
 [-0.46947439  0.54256004 -0.46341769 -0.46572975]]


In [5]:
Y = np.ones((4, 2))
print("Y =")
print(Y)

Y =
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [6]:
Z = X @ Y
print("Z =")
print(Z)

Z =
[[ 2.52916825  2.52916825]
 [ 1.87835721  1.87835721]
 [-0.85606179 -0.85606179]]


In [7]:
element_row1_col2 = Z[0, 1]
row2_all = Z[1, :]
print(f"第一行第二列: {element_row1_col2}")
print(f"第二行: {row2_all}")

第一行第二列: 2.5291682463487657
第二行: [1.87835721 1.87835721]


In [8]:
fro_norm = np.linalg.norm(Z, 'fro')
print(f"Frobenius 范数: {fro_norm}")

Frobenius 范数: 4.616873319476863
